import React from 'react';
import renderer, { act } from 'react-test-renderer';
import { randomUUID as mockRandomUUID } from 'node:crypto';
import { draftReducer, DraftRecipeProvider, useDraftRecipe, type DraftIngredientLine } from './DraftRecipeContext';
import type { Recipe } from '../../domain/recipes/types';

// jest-expo's autogenerated native-module mock for expo-crypto
// (node_modules/expo-crypto/mocks/ExpoCrypto.ts) stubs randomUUID() as
// `(): any {}`, i.e. it returns undefined under test. Override it here so
// buildRecipe() gets a real string id in this suite, the same way it would
// get a real UUID from the native module on-device.
jest.mock('expo-crypto', () => ({
  randomUUID: () => mockRandomUUID(),
}));

const oatsLine: DraftIngredientLine = {
  ingredientId: 'usda:1001', ingredientName: 'Oats, raw',
  quantity: { grams: 80, input: { amount: 80, unit: { kind: 'mass', symbol: 'g' } } },
};

describe('draftReducer', () => {
  const empty = { id: null, name: '', servings: 1, steps: [], ingredientLines: [] };

  it('START_NEW resets to an empty draft', () => {
    const state = draftReducer({ id: 'x', name: 'old', servings: 4, steps: ['a'], ingredientLines: [oatsLine] }, { type: 'START_NEW' });
    expect(state).toEqual(empty);
  });

  it('START_EDITING seeds the draft from a recipe and its resolved lines', () => {
    const recipe: Recipe = { id: 'recipe-1', name: 'Porridge', servings: 2, ingredients: [{ ingredientId: oatsLine.ingredientId, quantity: oatsLine.quantity }], steps: ['Simmer.'] };
    const state = draftReducer(empty, { type: 'START_EDITING', recipe, lines: [oatsLine] });
    expect(state).toEqual({ id: 'recipe-1', name: 'Porridge', servings: 2, steps: ['Simmer.'], ingredientLines: [oatsLine] });
  });

  it('SET_NAME/SET_SERVINGS/SET_STEPS update their field only', () => {
    let state = draftReducer(empty, { type: 'SET_NAME', name: 'Porridge' });
    state = draftReducer(state, { type: 'SET_SERVINGS', servings: 4 });
    state = draftReducer(state, { type: 'SET_STEPS', steps: ['Step 1'] });
    expect(state).toEqual({ ...empty, name: 'Porridge', servings: 4, steps: ['Step 1'] });
  });

  it('ADD_INGREDIENT_LINE appends a line', () => {
    const state = draftReducer(empty, { type: 'ADD_INGREDIENT_LINE', line: oatsLine });
    expect(state.ingredientLines).toEqual([oatsLine]);
  });

  it('REMOVE_INGREDIENT_LINE removes only the targeted line', () => {
    const secondLine: DraftIngredientLine = { ...oatsLine, ingredientId: 'usda:2002', ingredientName: 'Milk' };
    const withTwo = draftReducer(empty, { type: 'ADD_INGREDIENT_LINE', line: oatsLine });
    const withBoth = draftReducer(withTwo, { type: 'ADD_INGREDIENT_LINE', line: secondLine });
    const state = draftReducer(withBoth, { type: 'REMOVE_INGREDIENT_LINE', ingredientId: oatsLine.ingredientId });
    expect(state.ingredientLines).toEqual([secondLine]);
  });
});

describe('DraftRecipeProvider', () => {
  it('buildRecipe assigns a new UUID id when the draft has none', async () => {
    let hookResult: ReturnType<typeof useDraftRecipe>;
    function Consumer() {
      hookResult = useDraftRecipe();
      return null;
    }
    await act(async () => {
      renderer.create(
        <DraftRecipeProvider>
          <Consumer />
        </DraftRecipeProvider>,
      );
    });
    act(() => {
      hookResult!.startNew();
      hookResult!.setName('Porridge');
      hookResult!.setServings(2);
      hookResult!.setSteps(['Simmer.']);
      hookResult!.addIngredientLine(oatsLine);
    });
    const recipe = hookResult!.buildRecipe();
    expect(recipe.id).toEqual(expect.any(String));
    expect(recipe.id.length).toBeGreaterThan(0);
    expect(recipe).toEqual({
      id: recipe.id, name: 'Porridge', servings: 2, steps: ['Simmer.'],
      ingredients: [{ ingredientId: oatsLine.ingredientId, quantity: oatsLine.quantity }],
    });
  });

  it('buildRecipe keeps the existing id when editing', async () => {
    let hookResult: ReturnType<typeof useDraftRecipe>;
    function Consumer() {
      hookResult = useDraftRecipe();
      return null;
    }
    const recipe: Recipe = { id: 'recipe-1', name: 'Porridge', servings: 2, ingredients: [], steps: [] };
    await act(async () => {
      renderer.create(
        <DraftRecipeProvider>
          <Consumer />
        </DraftRecipeProvider>,
      );
    });
    act(() => {
      hookResult!.startEditing(recipe, []);
    });
    expect(hookResult!.buildRecipe().id).toBe('recipe-1');
  });
});
